services:
  calibre:
    image: linuxserver/calibre
    container_name: calibre
    restart: always
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - data:/config
    ports:
      - 81:8080
      - 8081:8081
  nginx:
    image: nginx
    container_name: nginx
    restart: always
    ports:
      - 80:80
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - data:/usr/share/nginx/html
    depends_on:
      - calibre
volumes:
  data: null
